export type AssuranceLevel = 'A0' | 'A1' | 'A2';
export type AccountState = 'active'|'recovery_pending'|'protected'|'frozen'|'closing'|'closed';
export interface Principal { issuer:string; subject:string; assurance:AssuranceLevel; method:'email'|'password'|'passkey'|'social'; authenticatedAt:number }
export interface User { userId:string; state:AccountState; cloudStorageEnabled:boolean; coolingOffUntil?:number }
export interface Session { sessionId:string; userId:string; assurance:AssuranceLevel; method:string; createdAt:number; lastSeenAt:number; absoluteExpiresAt:number; freshA2At?:number; revokedAt?:number; version:number }
export const canReadP2P3=(a:AssuranceLevel)=>a==='A2';
export const isFreshA2=(p:Principal,now:number,ms=600_000)=>p.assurance==='A2'&&now-p.authenticatedAt<=ms;
export function assertDataAccess(user:User,session:Session|undefined,now:number){if(!session)throw Error('session_required');if(session.assurance!=='A2')throw Error('a2_required');if(!user.cloudStorageEnabled)throw Error('cloud_storage_disabled');if(user.state!=='active')throw Error(`account_${user.state}`);return {coolingOff:!!user.coolingOffUntil&&now<user.coolingOffUntil}}
export class InMemorySessionStore { private m=new Map<string,Session>(); constructor(private inactivityMs=3_600_000){} create(s:Session){this.m.set(s.sessionId,structuredClone(s))} get(id:string,now:number){const s=this.m.get(id);if(!s||s.revokedAt||now>=s.absoluteExpiresAt||now-s.lastSeenAt>this.inactivityMs)return undefined;s.lastSeenAt=now;return structuredClone(s)} revoke(id:string,now:number){const s=this.m.get(id);if(s)s.revokedAt=now} revokeAll(uid:string,now:number){for(const s of this.m.values())if(s.userId===uid)s.revokedAt=now} }
type JwtPayload={iss:string;sub:string;aud:string;iat:number;exp:number;assurance:AssuranceLevel;method:string};
const te=new TextEncoder();
function b64u(b:Uint8Array){let s='';for(const x of b)s+=String.fromCharCode(x);return btoa(s).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_')}
function unb64u(s:string){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
export class LocalJwksIssuer { private pair?:CryptoKeyPair; readonly issuer='https://c1-auth.local/'; readonly audience='https://c1-api.local/'; readonly kid='c1-local-rs256'; private async keys(){if(!this.pair)this.pair=await crypto.subtle.generateKey({name:'RSASSA-PKCS1-v1_5',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['sign','verify']);return this.pair} async jwks(){const {publicKey}=await this.keys();const jwk=await crypto.subtle.exportKey('jwk',publicKey);return {keys:[{...jwk,kid:this.kid,alg:'RS256',use:'sig'}]}} async issue(i:{sub:string;assurance:AssuranceLevel;method:string;now:number;ttlSeconds?:number;issuer?:string;audience?:string}){const pair=await this.keys();const h=b64u(te.encode(JSON.stringify({alg:'RS256',typ:'JWT',kid:this.kid})));const p:JwtPayload={iss:i.issuer??this.issuer,sub:i.sub,aud:i.audience??this.audience,iat:Math.floor(i.now/1000),exp:Math.floor(i.now/1000)+(i.ttlSeconds??300),assurance:i.assurance,method:i.method};const pb=b64u(te.encode(JSON.stringify(p)));const msg=`${h}.${pb}`;const sig=await crypto.subtle.sign('RSASSA-PKCS1-v1_5',pair.privateKey,te.encode(msg));return `${msg}.${b64u(new Uint8Array(sig))}`} async verify(token:string,now:number){const [h,p,s]=token.split('.');if(!h||!p||!s)throw Error('jwt_shape');const header=JSON.parse(new TextDecoder().decode(unb64u(h)));if(header.alg!=='RS256'||header.kid!==this.kid)throw Error('jwt_header');const pair=await this.keys();if(!await crypto.subtle.verify('RSASSA-PKCS1-v1_5',pair.publicKey,unb64u(s),te.encode(`${h}.${p}`)))throw Error('jwt_signature');const x=JSON.parse(new TextDecoder().decode(unb64u(p))) as JwtPayload;if(x.iss!==this.issuer)throw Error('jwt_issuer');if(x.aud!==this.audience)throw Error('jwt_audience');if(x.exp<=Math.floor(now/1000))throw Error('jwt_expired');return x} }
