import type {Session,User} from './auth.js';import {assertDataAccess} from './auth.js';import {strictFields,validateOtherServiceName} from './input.js';
export interface CryptoProvider{encrypt(p:Uint8Array,aad:string):Promise<Uint8Array>;decrypt(c:Uint8Array,aad:string):Promise<Uint8Array>}
function webCryptoBytes(v:Uint8Array):Uint8Array<ArrayBuffer>{const out=new Uint8Array(v.byteLength);out.set(v);return out}
export class EphemeralCryptoProvider implements CryptoProvider{private k=crypto.subtle.generateKey({name:'AES-GCM',length:256},false,['encrypt','decrypt']);async encrypt(p:Uint8Array,aad:string){const iv=crypto.getRandomValues(new Uint8Array(12)),key=await this.k,out=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode(aad)},key,webCryptoBytes(p));const b=new Uint8Array(12+out.byteLength);b.set(iv);b.set(new Uint8Array(out),12);return b}async decrypt(c:Uint8Array,aad:string){const bytes=webCryptoBytes(c),key=await this.k,out=await crypto.subtle.decrypt({name:'AES-GCM',iv:bytes.slice(0,12),additionalData:new TextEncoder().encode(aad)},key,bytes.slice(12));return new Uint8Array(out)}}
export interface DeleteEvent{eventId:string;userId:string;recordId?:string;generation:number;deletedAt:number;type:'record'|'category'|'all'|'account';backupCutoff:number;schemaVersion:number}
export class LocalAppendOnlyJournal{private e:DeleteEvent[]=[];append(x:DeleteEvent){if(!this.e.some(y=>y.eventId===x.eventId))this.e.push(structuredClone(x))}listAfter(cutoff:number){return this.e.filter(x=>x.deletedAt>cutoff).map(x=>structuredClone(x))}}
export function replayDeletions<T extends{id:string}>(rows:T[],events:DeleteEvent[]){const ids=new Set(events.flatMap(e=>e.recordId?[e.recordId]:[]));return rows.filter(r=>!ids.has(r.id))}
export type LogEvent={eventType:string;opaqueUserId?:string;opaqueResourceId?:string;correlationId:string;result:'success'|'failure';errorCode?:string;durationMs?:number;appVersion:string;schemaVersion:number;assuranceLevel?:string};export class AllowlistLogger{lines:string[]=[];write(e:LogEvent){this.lines.push(JSON.stringify(e))}}
type ServiceInput={categoryId:string;serviceCatalogId?:string;otherServiceName?:string;usageStatus:'using'|'dormant'|'unknown';intentOverride?:'same'|'keep'|'delete'|'family'|'undecided';answers?:Record<string,string>;schemaVersion:1};const allowed=['categoryId','serviceCatalogId','otherServiceName','usageStatus','intentOverride','answers','schemaVersion'] as const;const answerKeys=new Set(['importantData','backup','handover','billing','recoveryUse','backupUse','paid','billingSource','asset','familyKnow','selfIdentify','balance','openTrade','recovery','dependency','purchase','subscription','mainLine','importance','sharedAdmin']);
export class InMemoryOwnerRepository{private rows=new Map<string,{recordId:string;ownerUserId:string;input:ServiceInput}>();private next=1;insert(uid:string,input:ServiceInput){const recordId=`r${this.next++}`;this.rows.set(recordId,{recordId,ownerUserId:uid,input:structuredClone(input)});return{recordId,ownerUserId:uid}}read(uid:string,id:string){const r=this.rows.get(id);return r?.ownerUserId===uid?structuredClone(r):undefined}}
export class ApplicationService{constructor(private repo:InMemoryOwnerRepository){}create(user:User,s:Session|undefined,raw:Record<string,unknown>,now:number){assertDataAccess(user,s,now);strictFields(raw,allowed);if(raw.schemaVersion!==1)throw Error('unsupported_schema_version');if(typeof raw.categoryId!=='string'||!/^[A-L]$/.test(raw.categoryId))throw Error('invalid_category');if(!['using','dormant','unknown'].includes(String(raw.usageStatus)))throw Error('invalid_usage_status');if(raw.otherServiceName!==undefined)validateOtherServiceName(raw.otherServiceName);if(raw.answers!==undefined){if(!raw.answers||typeof raw.answers!=='object'||Array.isArray(raw.answers))throw Error('invalid_answers');for(const[k,v]of Object.entries(raw.answers as Record<string,unknown>)){if(!answerKeys.has(k))throw Error(`unknown_answer:${k}`);if(typeof v!=='string'||!['yes','no','unknown','Apple','Google','carrier','other','high','medium','low'].includes(v))throw Error(`invalid_answer:${k}`)}}return this.repo.insert(s!.userId,raw as ServiceInput)}read(user:User,s:Session|undefined,id:string,now:number){assertDataAccess(user,s,now);return this.repo.read(s!.userId,id)}}
